tap "homebrew/cask"

# Terminal
cask "iterm2"
brew "zinit"

# IDE
cask "visual-studio-code"
cask "intellij-idea"
cask "goland"

# Core functions
brew "coreutils"
brew "fzf"
brew "autojump"
brew "tree"
brew "gnu-sed"
brew "telnet"
brew "expect"
brew "gpg"
brew "netcat"
brew "watch"

# Communication tools
cask "slack"
cask "microsoft-teams"
cask "skype-for-business"

# Dev tools
cask "kaleidoscope"
brew "yq"
brew "jq"
brew "bat"
brew "kafkacat"
brew "k6"
brew "dive"
brew "docker"
brew "docker-compose"
brew "insomnia"
brew "ansible"
cask "lepton"

# Dev tools management
brew "asdf"

# Environment management
brew "direnv"

# Source code management
brew "git"
brew "git-crypt"

# Utilities
brew "mas"
cask "coteditor"
brew "wireshark"
brew "mitmproxy"
brew "no-more-secrets"
brew "nnn"
brew "openvpn"
brew "1password-cli"
cask "spotify"
cask "kindle"

# Kubernetes tools
brew "k9s"
brew "k3d"
brew "stern"
brew "kubectx"
cask "kui"

# Cloud tools
brew "azure-cli"
brew "awscli"