# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.asdfpath]
# TODO zsh-defer 
inline = 'source /opt/homebrew/opt/asdf/libexec/asdf.sh'

[plugins.golangenv]
# TODO zsh-defer 
inline = 'source ~/.asdf/plugins/golang/set-env.zsh'

[plugins.forgit]
github = "wfxr/forgit"
apply = ["defer"]

[plugins.kubectl]
remote = 'https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/kubectl/kubectl.plugin.zsh'
apply = ["defer"]

[plugins.kubeswitch]
inline = 'zsh-defer eval "$(switcher init zsh)"'

