depends:
  - ./tools

actions:
  - action: package.install
    list:
      - k3d
      - kubectx
      - danielfoehrkn/switch/switch
      - kubespy
      - kui
      - krew
      - vendir  # Carvel
      - kapp    # Carvel
      - imgpkg  # Carvel
      - datawire/blackbird/telepresence-arm64

  - action: command.run
    command: sh
    args:
      - "-c"
      - "kubectl krew install < apps/kubernetes/files/krew-plugins.config"

  - action: command.run
    command: cargo
    args:
      - "install"
      - "kubetui"